[package]
name = "simple-game"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.4"
glam = { version = "0.12", features = ["bytemuck"] }
png-decoder = "0.1"
pollster = "0.2"
rect_packer = "0.2"
wgpu = "0.9"
winit = "0.24"

[build-dependencies]
naga = { version = "0.5", features = ["wgsl-in"] }
