[package]
name = "simple-game"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
glam = "0.12"
pollster = "0.2"
wgpu = "0.7"
winit = "0.24"

[build-dependencies]
shaderc = { version = "0.6", features = ["build-from-source"]}
