[package]
name = "simple-game"
version = "0.1.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
edition = "2018"
resolver = "2"

[features]
default = ["bevy"]
bevy = ["bevy_app", "bevy_core", "bevy_ecs", "bevy_time", "bevy_transform"]

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
fontdue = "0.4"
glam = { version = "0.24", features = ["bytemuck"] } # Tracks the version in bevy
png-decoder = "0.1"
pollster = "0.3"
rect_packer = "0.2"
wgpu = "0.18"
winit = "0.28"

bevy_app = { version = "0.12", default-features = false, optional = true }
bevy_core = { version = "0.12", default-features = false, optional = true }
bevy_ecs = { version = "0.12", default-features = false, optional = true }
bevy_time = { version = "0.12", default-features = false, optional = true }
bevy_transform = { version = "0.12", default-features = false, optional = true }

[build-dependencies]
naga = { version = "0.12", features = ["validate", "wgsl-in"] }

[[example]]
name = "bevy"
path = "examples/bevy_example.rs"
required-features = ["bevy"]
